import { Comment } from "./types";

export const comments: Comment[] = [
  {
    id: "comment-1",
    reviewId: "review-1",
    userId: "user-2",
    content: "I noticed the same lag in the interface. Did you try updating the firmware? The latest update improved the responsiveness for me.",
    upvotes: 12,
    downvotes: 0,
    createdAt: "2023-02-16T13:45:00Z",
  },
  {
    id: "comment-2",
    reviewId: "review-1",
    userId: "user-5",
    content: "Which streaming device did you end up using with it? I'm considering getting the same TV.",
    upvotes: 8,
    downvotes: 0,
    createdAt: "2023-02-17T10:20:00Z",
  },
  {
    id: "comment-3",
    reviewId: "review-1",
    userId: "user-1",
    content: "I used a Roku Streaming Stick+. Works great with this TV and the setup was super easy.",
    upvotes: 15,
    downvotes: 0,
    createdAt: "2023-02-17T15:10:00Z",
    parentId: "comment-2",
  },
  {
    id: "comment-4",
    reviewId: "review-3",
    userId: "user-4",
    content: "How do they perform for phone calls? Can people hear you clearly in noisy environments?",
    upvotes: 6,
    downvotes: 1,
    createdAt: "2023-03-01T09:30:00Z",
  },
  {
    id: "comment-5",
    reviewId: "review-3",
    userId: "user-2",
    content: "Phone call quality is excellent. The microphones do a great job of picking up your voice while filtering out background noise. I've taken calls while walking on busy streets and the person on the other end could hear me clearly.",
    upvotes: 14,
    downvotes: 0,
    createdAt: "2023-03-01T12:45:00Z",
    parentId: "comment-4",
  },
  {
    id: "comment-6",
    reviewId: "review-6",
    userId: "user-3",
    content: "Have you experienced any overheating issues while using the camera for extended periods?",
    upvotes: 8,
    downvotes: 0,
    createdAt: "2023-06-21T14:15:00Z",
  },
  {
    id: "comment-7",
    reviewId: "review-6",
    userId: "user-1",
    content: "No overheating issues so far, even when recording 4K video for about 20 minutes straight. The phone got warm but not uncomfortably hot.",
    upvotes: 11,
    downvotes: 0,
    createdAt: "2023-06-22T08:30:00Z",
    parentId: "comment-6",
  },
  {
    id: "comment-8",
    reviewId: "review-8",
    userId: "user-5",
    content: "Does it track specific workouts like weightlifting or yoga? Or is it mainly focused on cardio activities?",
    upvotes: 5,
    downvotes: 0,
    createdAt: "2023-08-16T11:20:00Z",
  },
  {
    id: "comment-9",
    reviewId: "review-8",
    userId: "user-2",
    content: "It has specific tracking modes for over 20 activities, including weightlifting, yoga, swimming, and various cardio exercises. For weightlifting, it can count reps for certain exercises, which is useful. The yoga tracking mainly focuses on heart rate and calories burned rather than specific poses.",
    upvotes: 9,
    downvotes: 0,
    createdAt: "2023-08-16T14:05:00Z",
    parentId: "comment-8",
  },
  {
    id: "comment-10",
    reviewId: "review-7",
    userId: "user-4",
    content: "Have you tried using battery saver mode? I found it extends the battery life significantly without compromising too much on performance.",
    upvotes: 7,
    downvotes: 1,
    createdAt: "2023-07-03T09:40:00Z",
  },
]; 