import { Product } from "./types";

export const products: Product[] = [
  {
    id: "product-1",
    name: "Ultra HD Smart TV 55\"",
    description: "Experience stunning 4K resolution with this smart TV featuring HDR, Dolby Vision, and built-in streaming apps.",
    category: "Electronics",
    image: "https://images.pexels.com/photos/5282269/pexels-photo-5282269.jpeg?auto=compress&cs=tinysrgb&w=800",
    brand: "TechVision",
    averageRating: 4.5,
    totalReviews: 128,
    createdAt: "2023-01-10T12:00:00Z",
  },
  {
    id: "product-2",
    name: "Premium Wireless Headphones",
    description: "Immersive sound quality with active noise cancellation, 30-hour battery life, and comfortable over-ear design.",
    category: "Audio",
    image: "https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg?auto=compress&cs=tinysrgb&w=800",
    brand: "SoundMaster",
    averageRating: 4.7,
    totalReviews: 95,
    createdAt: "2023-02-05T14:30:00Z",
  },
  {
    id: "product-3",
    name: "Professional Blender",
    description: "High-performance blender with variable speed control, pulse function, and durable stainless steel blades.",
    category: "Kitchen",
    image: "https://images.pexels.com/photos/3625372/pexels-photo-3625372.jpeg?auto=compress&cs=tinysrgb&w=800",
    brand: "KitchenPro",
    averageRating: 4.3,
    totalReviews: 72,
    createdAt: "2023-03-15T09:45:00Z",
  },
  {
    id: "product-4",
    name: "Ergonomic Office Chair",
    description: "Adjustable chair with lumbar support, breathable mesh back, and padded armrests for all-day comfort.",
    category: "Furniture",
    image: "https://images.pexels.com/photos/1957478/pexels-photo-1957478.jpeg?auto=compress&cs=tinysrgb&w=800",
    brand: "ComfortPlus",
    averageRating: 4.1,
    totalReviews: 64,
    createdAt: "2023-04-20T11:15:00Z",
  },
  {
    id: "product-5",
    name: "Smartphone Pro Max",
    description: "Cutting-edge smartphone with advanced camera system, powerful processor, and all-day battery life.",
    category: "Electronics",
    image: "https://images.pexels.com/photos/1786433/pexels-photo-1786433.jpeg?auto=compress&cs=tinysrgb&w=800",
    brand: "TechGiant",
    averageRating: 4.8,
    totalReviews: 156,
    createdAt: "2023-05-12T10:00:00Z",
  },
  {
    id: "product-6",
    name: "Smart Fitness Watch",
    description: "Track your workouts, heart rate, sleep, and more with this water-resistant smart fitness tracker.",
    category: "Wearables",
    image: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=800",
    brand: "FitTech",
    averageRating: 4.4,
    totalReviews: 88,
    createdAt: "2023-06-08T08:30:00Z",
  },
  {
    id: "product-7",
    name: "Robot Vacuum Cleaner",
    description: "Intelligent vacuum with mapping technology, powerful suction, and app control for effortless cleaning.",
    category: "Home",
    image: "https://images.pexels.com/photos/4108270/pexels-photo-4108270.jpeg?auto=compress&cs=tinysrgb&w=800",
    brand: "CleanSmart",
    averageRating: 4.2,
    totalReviews: 59,
    createdAt: "2023-07-05T13:45:00Z",
  },
  {
    id: "product-8",
    name: "Premium Coffee Maker",
    description: "Programmable coffee machine with built-in grinder, thermal carafe, and customizable brewing options.",
    category: "Kitchen",
    image: "https://images.pexels.com/photos/2374794/pexels-photo-2374794.jpeg?auto=compress&cs=tinysrgb&w=800",
    brand: "BrewMaster",
    averageRating: 4.6,
    totalReviews: 83,
    createdAt: "2023-08-18T15:20:00Z",
  },
]; 