import { Review } from "./types";

export const reviews: Review[] = [
  {
    id: "review-1",
    productId: "product-1",
    userId: "user-1",
    title: "Excellent picture quality, but software could be better",
    content: "I've had this TV for about a month now, and I'm generally very pleased with it. The 4K picture quality is stunning, especially when watching HDR content. Colors are vibrant and blacks are deep. However, the smart TV interface is a bit laggy at times and the app selection could be better. I ended up connecting a streaming device for a smoother experience. Overall, great value for the price.",
    rating: 4,
    upvotes: 45,
    downvotes: 3,
    images: ["https://images.pexels.com/photos/5024493/pexels-photo-5024493.jpeg?auto=compress&cs=tinysrgb&w=800"],
    createdAt: "2023-02-15T09:30:00Z",
  },
  {
    id: "review-2",
    productId: "product-1",
    userId: "user-3",
    title: "Perfect for my living room setup",
    content: "This TV exceeded my expectations! The picture quality is incredible, and the thin bezels make it look very sleek on my wall. Setup was straightforward, and I was streaming content within minutes. The built-in speakers are decent, but I connected a soundbar for a more immersive experience. The smart features work well, and I haven't experienced any lag with the interface. Highly recommend!",
    rating: 5,
    upvotes: 62,
    downvotes: 1,
    createdAt: "2023-03-05T14:45:00Z",
  },
  {
    id: "review-3",
    productId: "product-2",
    userId: "user-2",
    title: "Best headphones I've ever owned",
    content: "These headphones are absolutely worth every penny. The noise cancellation is phenomenal - I use them during flights and can barely hear the engine noise. Sound quality is exceptional with clear highs and deep, punchy bass. Battery life is as advertised, getting around 28-30 hours on a single charge. The build quality feels premium, and they're comfortable enough to wear for extended periods. The app provides useful customization options as well.",
    rating: 5,
    upvotes: 78,
    downvotes: 2,
    images: [
      "https://images.pexels.com/photos/3394665/pexels-photo-3394665.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    createdAt: "2023-02-28T11:20:00Z",
  },
  {
    id: "review-4",
    productId: "product-2",
    userId: "user-4",
    title: "Good sound but uncomfortable for long periods",
    content: "The sound quality and noise cancellation on these headphones are excellent, no complaints there. However, I find them uncomfortable to wear for more than an hour or so due to the clamping force. The ear cups also get quite warm. Battery life is solid, and the controls are intuitive. If the comfort issues were addressed, these would be perfect.",
    rating: 3,
    upvotes: 24,
    downvotes: 8,
    createdAt: "2023-03-10T16:15:00Z",
  },
  {
    id: "review-5",
    productId: "product-3",
    userId: "user-5",
    title: "Powerful blender that handles everything",
    content: "I've been using this blender daily for smoothies, soups, and even homemade nut butters. It's powerful enough to crush ice and blend frozen fruits with ease. The variable speed control is great for different textures, and the pulse function works well for quick chopping. Cleaning is simple - just blend warm water with a drop of dish soap. Only minor complaint is the noise level, but that's expected with such a powerful motor.",
    rating: 5,
    upvotes: 36,
    downvotes: 1,
    createdAt: "2023-04-05T08:45:00Z",
  },
  {
    id: "review-6",
    productId: "product-5",
    userId: "user-1",
    title: "Outstanding camera and performance",
    content: "This is my third phone from this brand, and they keep getting better. The camera system is incredible - photos in low light are clear and detailed, and the zoom capability is impressive. Performance is snappy with no lag even when running multiple apps. Battery easily lasts all day with my fairly heavy usage. The screen is bright and vibrant. My only gripe is that it's quite expensive, but you get what you pay for in terms of quality and features.",
    rating: 5,
    upvotes: 94,
    downvotes: 4,
    images: ["https://images.pexels.com/photos/3587818/pexels-photo-3587818.jpeg?auto=compress&cs=tinysrgb&w=800"],
    createdAt: "2023-06-20T13:30:00Z",
  },
  {
    id: "review-7",
    productId: "product-5",
    userId: "user-3",
    title: "Great phone with one major flaw",
    content: "This phone has excellent build quality, an amazing display, and the performance is top-notch. The camera takes stunning photos in good lighting. However, battery life is disappointing - I'm barely making it through a day with moderate use. Fast charging helps, but I was expecting better battery performance at this price point. Software updates have been regular, which is nice. Overall, it's a good phone, but the battery issue is holding me back from giving it 5 stars.",
    rating: 4,
    upvotes: 41,
    downvotes: 6,
    createdAt: "2023-07-02T10:15:00Z",
  },
  {
    id: "review-8",
    productId: "product-6",
    userId: "user-2",
    title: "Accurate fitness tracking with stylish design",
    content: "I've been using this fitness watch for three months now, and I'm impressed with its accuracy and features. The heart rate monitoring seems consistent with my chest strap monitor, and the GPS tracking is precise. Sleep analysis provides useful insights, and I appreciate the stress tracking feature. Battery life is about 6 days with moderate use, which is convenient. The watch looks professional enough to wear at work too. The companion app is well-designed and easy to navigate.",
    rating: 5,
    upvotes: 52,
    downvotes: 3,
    createdAt: "2023-08-15T09:00:00Z",
  },
]; 